# Generated by Django 4.2.6 on 2023-10-31 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='classificacao',
            new_name='nome',
        ),
    ]
